name: Terraform Lint

description: Run Terraform lint checks

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Format Check
      shell: bash
      run: terraform fmt -check -recursive

    - name: Terraform Init
      shell: bash
      run: terraform init -backend=false

    - name: Terraform Validate
      shell: bash
      run: terraform validate

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4

    - name: TFLint
      shell: bash
      run: |
        tflint --init
        tflint