name: SCM Test Workflow

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create file
        run: |
          echo "Hello from build job" > version.txt

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: version-file
          path: version.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: version-file

      - name: Display file
        run: |
          cat version.txt