name: SCM Test Workflow

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.ver.outputs.version }}

    steps:
      - name: Set version output
        id: ver
        run: echo "version=1.2.3" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Use version from build job
        run: |
          echo "Version is ${{ needs.build.outputs.version }}"
