name: matrix test workflow

on:
  workflow_dispatch:
  push:

jobs:
  terraform:
    strategy:
      matrix:
        version: [1.8.5, 1.9.8]

    runs-on: ubuntu-latest

    steps:
      - run: echo "Terraform version is ${{ matrix.version }}"